---
version: '3.8'
services:
  pgdb:
    image: postgres:16.2
    container_name: atest-pgdb
    environment:
      - POSTGRES_DB=ates
      - POSTGRES_USER=popug
      - POSTGRES_PASSWORD=pgdbpassword
    ports:
      - '5432:5432'
    volumes:
      - ates-pgdb-data:/var/lib/postgresql/data

  kafka-broker:
    image: confluentinc/cp-kafka:7.6.0
    hostname: broker
    container_name: ates-kafka-broker
    ports:
      - "9092:9092"
      - "9101:9101"
    volumes:
      - ates-kafka-data:/var/lib/kafka/data
      - ates-kafka-secrets:/etc/kafka/secrets
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

volumes:
  ates-kafka-data: {}
  ates-kafka-secrets: {}
  ates-pgdb-data: {}
